### PR TITLE
chore(README): update contributing section

### PR DESCRIPTION
**Pull request by vdice**
Updates and re-words the DCO section.

If this looks good, we can add it to the rest of the repos in this org and then add the [dco bot](https://github.com/apps/dco) for automated verification.

Ref https://github.com/brigadecore/brigade/issues/853

### CODE REVIEW

**Review by adamreese — APPROVED** [review]

**Comment by vdice** [comment]
I've added this same doc to the main Brigade repo in https://github.com/brigadecore/brigade/pull/855.

Would it be possible for related projects (such as this) to link to the [Contributing](https://github.com/brigadecore/brigade/pull/855/files#diff-6a3371457528722a734f3c51d9238c13) doc in the main Brigade repo, to avoid duplication?  Or must each repo house its own?

**Review by dgkanatsios — COMMENTED** [review]
Q: on signing, are you talking about [GPG signing](https://help.github.com/en/articles/signing-commits)? If so, we could include some relevant instructions for new users

**Comment by vdice** [comment]
@dgkanatsios good question -- this same subtlety confused me at first as well.  I believe the sign-off process for affirming DCO is different from GPG signing a commit.  (Reading up on the [dco bot](https://github.com/apps/dco) description helped clarify the distinction for me.)

However, I'd totally encourage adding a doc/link showing contributors how to GPG sign their commits, though perhaps in a separate PR.

**Comment by dgkanatsios** [comment]
gotcha - DCO is new for me so I wondered :) So, DCO signing will be a requirement, whereas GPG not (even though heavily encouraged)?

**Comment by vdice** [comment]
> So, DCO signing will be a requirement, whereas GPG not (even though heavily encouraged)?

I'm unsure on the actual requirements now that Brigade is a CNCF sandbox project, though adding DCO was mentioned in the dev meetings and in https://github.com/brigadecore/community/pull/2, so I wanted to get something started.  So these questions/distinctions are very helpful!

Looking for confirmation from other members to make sure I'm/we're on the right track here.  cc @radu-matei @technosophos

**Comment by radu-matei** [comment]
@vdice -- re: contribution guide -- the sign-off process would be the same for all repos, but the actual contributing guide most likely would differ.

**Review by radu-matei — APPROVED** [review]
LGTM

**Comment by vdice** [comment]
Updated to link to canonical sign-off instructions in brigadecore/brigade.

**Pull request merged**
