### PR TITLE
fix(brigade): vacuum imagePullSecrets

### PR DESCRIPTION
**Pull request by vdice**
* Fixes the imagePullSecrets section for the ServiceAccount section of the Brigade Vacuum component

### CODE REVIEW

**Comment by krancour** [comment]
Should we release after this? As it stand now, this must be a bug, no?

**Comment by vdice** [comment]
Yup, we'd want to cut a patch release of the chart after this.

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
> Yup, we'd want to cut a patch release of the chart after this.

sgtm

**Comment by vdice** [comment]
(https://github.com/brigadecore/charts/releases/tag/brigade-v1.7.1 cut with this fix)

**Pull request merged**
